name: CI

on:
  push:
   branches:
    - main:  
    
  pull_request:
   branches:
    - main:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m pip install pytest .

      - name: Run Tests
        run: pytest -v






